[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
diesel = { version = "2.2.0", features = ["postgres","chrono"] }
dotenvy = "0.15.7"
uuid ={version="1.17.0",features=["v4"]}

